import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Toaster} from 'react-hot-toast'
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable:'--font-sans' });

export const metadata: Metadata = {
  title: "Digital Oasis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <head>
          <script src="https://code.jquery.com/jquery-3.7.1.js" />
          <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/crypto-js.min.js" />
          <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/hmac-sha256.min.js" />
          <script src="https://cdnjs.cloudflare.com/ajax/libs/crypto-js/3.1.9-1/enc-base64.min.js" />
          <script src="https://www.google.com/recaptcha/api.js" async defer ></script>

        </head>
      <body className={cn("bg-background min-h-screen font-sans antialiased",inter.variable )}>
                  <Toaster />
                  {children}
      </body>
    </html>
  );
}
